### ISSUE TITLE
Manage multiple binding sites

### ISSUE THREAD

**Issue by BerndDoser** [HITS-MCM/gromacs-ramd#15]
Multiple binding sites with independent force magnitude will be managed and monitored simultaneously. The simulation will end premature if all COM distances between ligand and receptor are larger than corresponding maximal distances. The RAMD group parameters will be designed equally to the PULL group parameters. The number of bindings sites is given with `ramd-ngroups`. The binding site depending parameters are denoted with the prefix `ramd-group[n]`, where `n` is the group number.

The mdp parameters will change as follows:

### RAMD v1
```
ramd                     = yes
ramd-seed                = 9876
ramd-receptor            = Protein
ramd-ligand              = INH
ramd-force               = 600.0
ramd-r-min-dist          = 0.025
ramd-max-dist            = 4.0
ramd-eval-freq           = 50
ramd-force-out-freq      = 100
```
### RAMD v2
```
ramd                     = yes
ramd-seed                = 9876
ramd-ngroups             = 1
ramd-group1-receptor     = Protein
ramd-group1-ligand       = INH
ramd-group1-force        = 600.0
ramd-group1-r-min-dist   = 0.025
ramd-group1-max-dist     = 4.0
ramd-eval-freq           = 50
ramd-force-out-freq      = 100
```

**Comment by DKokh** [comment]
the standard ramd-r-min-dist is 0.0025 nm

**Comment by BerndDoser** [comment]
Yes, the default value of ramd-group[n]r-min-dist is still 0.0025 nm. The mdp parameters above are just an input example. If the paramter is not listed in the mdp file, the default value of 0.0025 nm will be taken.
