### ISSUE TITLE
Units for the ramd-inputs

### ISSUE THREAD

**Issue by kellegra** [HITS-MCM/gromacs-ramd#17]
Hi there, 

I am familiar to RAMD and NAMD, but wanted to try out the RAMD implementation in GROMACS. 
I am using GROMACS-2019.4-RAMD-1.0. 

In a sample gromacs_ramd.mdp file ramd-r-mind-dist and ramd-max-dist are mentioned to be in nm. When I started the simulation it aborts after a few seconds, telling the displacement of the ligand is greater than the cutoff (distance is 6.8). 
When I draw the coordinates in PyMOL and measure the distance, these are 6.8 Angstroms. Ramd-max-dist was defined equal to 2.5. So I would guess ramd-max-dist is given in Angstroms not in nm? 

Could you please tell me if both, ramd-max-dist and ramd-r-min-dist have to be in Angstroms or nm? 
And could you also clarify again whether the unit for ramd-force is correct (kJ mol-1 nm-1)?

Best
Gerald

**Comment by BerndDoser** [comment]
Hi Gerald,

thanks for your report. The units in the documentation should be correct (nm and kJ mol-1 nm-1). If I set ramd-max-dist to 4.0 nm the simulation aborts with a receptor-ligand COM distance of 4.02646 nm.

Output:
```
==== RAMD ==== evaluation 209450
==== RAMD ==== COM ligand position at [6.9189 ,2.13004 ,2.44481]
==== RAMD ==== COM receptor position at [3.68769 ,3.5858 ,4.27185]
==== RAMD ==== Distance between COM of receptor and COM of ligand is 3.98723
==== RAMD ==== Previous COM ligand position at 6.88821 ,2.15077 ,2.452]
==== RAMD ==== Previous COM receptor position at 3.68967 ,3.58652 ,4.2719]
==== RAMD ==== Change in receptor-ligand distance since last RAMD evaluation is 0.0389704
==== RAMD ==== evaluation 209500
==== RAMD ==== COM ligand position at [6.95324 ,2.11111 ,2.43888]
==== RAMD ==== COM receptor position at [3.68658 ,3.58744 ,4.27239]
==== RAMD ==== Distance between COM of receptor and COM of ligand is 4.02646
==== RAMD ==== Maximal distance between ligand and receptor COM is reached.
==== RAMD ==== GROMACS will be stopped after 209500 steps.
```

Best regards,
Bernd

**Comment by kellegra** [comment]
Hey Bernd, 
thx for your reply! 
My problem that the RAMD simulation stops after 50 steps of simulation time still remains. I followed the tutorial on kbbox. I decided to start from a new NVT simulation due to something could have went wrong prevously. 

NVT and NPT runs look fine so far. When I start the RAMD run it aborts after 50 steps, cause the distance is > 6 nm. Threshold is 2.5 nm. 
Then I had a look at the last RAMD frame and the COMs were 1.1 nm apart only?!

What am I  overlooking here? If it makes things easier we could change to German. 

Output: 

```
``==== RAMD ==== evaluation 50
==== RAMD ==== COM ligand position at [2.42658 ,1.2378 ,5.70149]
==== RAMD ==== COM receptor position at [2.01008 ,7.77483 ,4.9308]
==== RAMD ==== Distance between COM of receptor and COM of ligand is 6.59546
==== RAMD ==== Maximal distance between ligand and receptor COM is reached.
==== RAMD ==== GROMACS will be stopped after 50 steps.
```

.mdp file: 

```
`integrator                       = md
dt                              = 0.002
nsteps                           = 20000000

nstlog                          = 2500
nstenergy                        = 2500
nstxout-compressed               = 500

continuation                     = yes
constraints                      = h-bonds
constraint-algorithm             = lincs

cutoff-scheme                   = Verlet
coulombtype                     = PME
rcoulomb                        = 1.0

vdwtype                         = Cut-off
DispCorr                        = EnerPres

ramd                            = yes
ramd-seed                       = 981   ;  XX will be  replaced by the trajectory number
ramd-force                      = 585.2      ; 585.2 kJ mol-1 nm-1  =  14 kcal/mol A *10*4.18
ramd-eval-freq                  = 50  ; number of steps in each RAMD cycle
ramd-r-min-dist                 = 0.0025       ; nm
ramd-force-out-freq              = 10
ramd-max-dist                   = 2.5         ; nm
ramd-receptor                   = Protein
ramd-ligand                      = LIG

comm-mode                        = Linear
nstcomm                         = 100
comm_grps                       = System

tinit                           = 0.000
nstxout                         = 5000
nstvout                          = 5000
compressed-x-precision   = 500
compressed-x-grps                = SYSTEM

pbc                             = xyz
rlist                           = 1.0
fourierspacing                  = 0.12
pme_order                       = 4
ewald_geometry                  = 3d
ewald-rtol                       = 1e-5
ewald-rtol-lj                    = 1e-5
vdw-modifier                     = Potential-shift
rvdw-switch                      = 0.0
rvdw                             = 1.0

tcoupl                          = Nose-Hoover
tc_grps                         = Protein_LIG_NAP    Water_and_ions
tau_t                    = 1.0    1.0
ref_t                    = 300 300

Pcoupl                           = Parrinello-Rahman
pcoupltype                       = isotropic
tau_p                    = 5.0
compressibility                 = 4.5e-5
ref_p                           = 1.0
gen_vel                          = no
```
`
Best 
Gerald

**Comment by BerndDoser** [comment]
Hi Gerald,

laut Ausgabe sind die COM Positionen [2.42658, 1.2378, 5.70149] fuer den Liganden und [2.01008, 7.77483, 4.9308], was einem Abstand von 6.6 nm entspricht. Wie bestimmst Du die COM Positionen? Du kannst mir gerne Deine Input-Dateien schicken. Dann kann ich mal drueberschauen.

Gruss
Bernd

**Comment by kellegra** [comment]
Hi Bernd, 



ich habe dir meine Inputs in den Anhang gepackt. 

Die state.cpt ist vom NPT-Run. 

In submit.sh steht, wie ich die Simulation starte und sollte analog zum kbbox-Tutorial sein. 



Um die Distanz zu messen, habe ich die xtc-Trajektorie von der RAMD-Simulation "gecentert" (trajconv -center -pbc mol
-ur compact) und den letzten Frame als pdb ausgeben lassen (trjconv -dump). Die pdb-Datei dann in PyMOL geöffnet,
pseudoatome für die COMs von Protein und Ligand erstellt und schließlich die Distanz der Pseudoatome gemessen. 



Ich noch nicht so mit GROMACS vertraut und habe irgendwo einen gravierenden Input-Fehler den ich nicht finde. 



Viele Grüße
Gerald




 
Von: Bernd Doser <notifications@github.com> 
Gesendet: Montag, 15. Februar 2021 10:00
An: HITS-MCM/gromacs-ramd <gromacs-ramd@noreply.github.com>
Cc: kellegra <gerald.keller@kabelmail.de>; Author <author@noreply.github.com>
Betreff: Re: [HITS-MCM/gromacs-ramd] Units for the ramd-inputs (#17)

 
Hi Gerald,
laut Ausgabe sind die COM Positionen [2.42658, 1.2378, 5.70149] fuer den Liganden und [2.01008, 7.77483, 4.9308], was
einem Abstand von 6.6 nm entspricht. Wie bestimmst Du die COM Positionen? Du kannst mir gerne Deine Input-Dateien
schicken. Dann kann ich mal drueberschauen.
Gruss
Bernd

**Comment by BerndDoser** [comment]
Source of this issue is #18.
