### ISSUE TITLE
A RAMD run is likely not to restart properly. 

### ISSUE THREAD

**Issue by physicshinzui** [HITS-MCM/gromacs-ramd#23]
# environment
- version 2020.5-dev-UNCHECKED

# Detail
After the first RAMD run, I restarted the run by using the following command: 
```
gmx mdrun -deffnm ramd_prod_0 -s ramd_prod_0.tpr -cpi ramd_prod_0.cpt -noappend -ntmpi 4 -ntomp 1
```
These files ramd_prod_0.cpt was generated by the first RAMD run, which seemed to work properly.
However, the restarted run lasted for a long time even though I set a small number of steps. 
Plus, while the simulation is running, I noticed that it never progressed. 
Let me put log files:
[in_out_files.zip](https://github.com/HITS-MCM/gromacs-ramd/files/6096797/in_out_files.zip)
- This zip file includes `ramd_prod_0.tpr` and `ramd_prod_0.cpt` that were used to restart in the above command. 
- `*.part0002.*` is the files of the initial run. 
- `*.part0002.*` is the files of the restarted run that I failed. 

Could you help me what were wrong? 
I look forward to hearing from you.

**Comment by BerndDoser** [comment]
Thanks for your feedback. The restart was not tested so far. I can imagine that some data could be missing in the cpt-file. I will take a look.

**Comment by BerndDoser** [comment]
I am not able to reproduce your issue with the latest release [gromacs-2020.5-ramd-2.0-rc2](https://github.com/HITS-MCM/gromacs-ramd/releases/tag/gromacs-2020.5-ramd-2.0-rc2). I start the simulation with
```
gmx mdrun -s ramd_prod_0.tpr -ramd -nsteps 1000000
```
stop it with `Ctrl-C` and restart it successfully with
```
gmx mdrun -s ramd_prod_0.tpr -ramd -cpi state.cpt -noappend -nsteps 1000000
```
Could you please check it again using the `-ramd` flag to track the RAMD distance file.

**Comment by physicshinzui** [comment]
Thank you for your check :) 
I have also executed the command you did, but there is only one difference:
```
gmx mdrun -s ramd_prod_0.tpr -ramd -nsteps 1000000
Ctrl + C
gmx mdrun -s ramd_prod_0.tpr -ramd -nsteps 100 #< This option "-nsteps 100" is the only difference. 
```
As you said, to restart succeeds, but I could not finish it regardless of "-nsteps 100". 
I am wondering whether you could finish the restart run. 

Perhaps, the version I am using may be different from gromacs-2020.5-ramd-2.0-rc2, so I'll try it as well.

Thanks,

**Comment by BerndDoser** [comment]
Unfortunately, I can still not reproduce your reported behavior. All simulations, no matter if restarted or using nsteps, stops successfully after the maximal number of steps is reached. The RAMD stopping criteria (COM distance of receptor and ligand larger than 5 nm) is unreachable using a residue as ligand. Do you see an continuous output in the ramd.xvg file or is the process totally hanging?

**Comment by BerndDoser** [comment]
Please reopen if the issue still exist.
