### ISSUE TITLE
ramd MD trajectories look strange

### ISSUE THREAD

**Issue by satvikkg** [HITS-MCM/gromacs-ramd#25]
Hi, I just ran the ramd tutorial (https://kbbox.h-its.org/toolbox/tutorials/estimation-of-relative-residence-times-of-protein-ligand-complexes-using-random-acceleration-molecular-dynamics-ramd-implementation-in-gromacs/). I have attached the output @ [test-tramd-run.zip](https://github.com/HITS-MCM/gromacs-ramd/files/6761144/test-tramd-run.zip). I have no idea why this is happening. Please take a look at the output trajectories. I was hoping you could help me figure out the issue.

**Comment by BerndDoser** [comment]
Thanks for your report. Unfortunately, I cannot find any problem with the trajectory. The protein is divided into different periodic boxes, which always looks a bit weird in visualization programs like vmd or pymol. Could you please describe your issue more detailed?

**Comment by satvikkg** [comment]
I have tried pymol, VMD and chimera. This is how my trajectory looks.
![image](https://user-images.githubusercontent.com/51278890/124585647-1fbcbc00-de73-11eb-84cc-f0ba6fc42971.png)
I want to create a movie of the trajectory. What visualization program do you recommend to view the trajectories ?

**Comment by BerndDoser** [comment]
This is a well-known problem (not related to RAMD) of visualization molecular structures on the periodic boundary. You can use [trjconv](https://manual.gromacs.org/documentation/5.1/onlinehelp/gmx-trjconv.html) to center the protein.
