### ISSUE TITLE
how do i install ramd when compiling gromacs

### ISSUE THREAD

**Issue by Byun-jinyoung** [HITS-MCM/gromacs-ramd#27]
Dear RAMD developers,
I tried to install gromacs-ramd when I install GROMACS.
Is there any installation instructions?

Sincerely,
Thank you:)

Jinyoung

**Comment by BerndDoser** [comment]
Hi @Byun-jinyoung,

GROMACS-RAMD is a patched version of GROMACS. Therefore, the installation instructions of GROMACS-RAMD are identical to GROMACS. See http://manual.gromacs.org/documentation/2020/install-guide/index.html.
