### ISSUE TITLE
Compilation mistake

### ISSUE THREAD

**Issue by RomainLaunay** [HITS-MCM/gromacs-ramd#39]
Hello,

I have tried to compile gromacs2023.4-ramd-2.1 and I have the following errors when I run a ramd_simulation I have the following error :

Command line:
  gmx grompp -f gromacs_ramd.mdp -c gromacs.gro -o gromacs_ramd.tpr -t state.cpt -maxwarn 2 -n index.ndx

WARNING 1 [file gromacs_ramd.mdp, line 64]:
  Unknown left-hand 'ramd-force' in parameter file

WARNING 2 [file gromacs_ramd.mdp, line 64]:
  Unknown left-hand 'ramd-r-min-dist' in parameter file

WARNING 3 [file gromacs_ramd.mdp, line 64]:
  Unknown left-hand 'ramd-max-dist' in parameter file

WARNING 4 [file gromacs_ramd.mdp, line 64]:
  Unknown left-hand 'ramd-receptor' in parameter file

WARNING 5 [file gromacs_ramd.mdp, line 64]:
  Unknown left-hand 'ramd-ligand' in parameter file

The error seems to come from the compilation of RAMD. Indeed, I have already compiled gromacs2023.4 without RAMD and all run fine.

My compilation command for gromacs2023.4-ramd-2.1 was the following : 
**cmake .. -DGMX_MPI=OFF -DCMAKE_PREFIX_PATH=/usr/local/fftwf -DREGRESSIONTEST_DOWNLOAD=OFF -DREGRESSIONTEST_PATH=../regressiontests-2023.4 -DGMX_GPU=CUDA -DCMAKE_INSTALL_PREFIX=/usr/local/gromacs-2023.4 -DGMX_CUDA_TARGET_COMPUTE="60;75;86" > cmake.log

make
make check
sudo make install**

Did you have any idea of what is the reason of the wrong compilation?

Best regards,

Romain

**Comment by BerndDoser** [comment]
Dear Romain,

Thanks for reporting. It appears that you are using the deprecated mdp parameters of RAMD v1 (see [release notes](https://github.com/HITS-MCM/gromacs-ramd/releases/tag/gromacs-2020.5-ramd-2.0)).

Please find the new mdp parameters in the [README](https://github.com/HITS-MCM/gromacs-ramd/blob/main/README.md).

Best regards,
Bernd

**Comment by BerndDoser** [comment]
I'm closing this issue for now. If there are any problems or questions, please feel free to reopen it or create a new issue.
