### ISSUE TITLE
IFP -generation

### ISSUE THREAD

**Issue by haoxuanluo731** [HITS-MCM/gromacs-ramd#46]
I want to ask a question，when I have finish the task about ramd，I want to use MD-iFP to generation IFP，but I find the question 
<img width="869" alt="image" src="https://github.com/user-attachments/assets/5883efc3-7d50-478e-9c90-cff263b73ab9">
But when I run the example in your github，It do not have this problem，I want to know what happen about this problem

this is my .py
![Uploading 屏幕截图 2024-09-03 202801.png…]()

**Comment by StefanGIT** [comment]
Sorry, i did not understand your problem. If you run the example we provide, it does work, but when you run your own analysis you get the problem shown in the image that the trajectory cannot be found?

Did you check if you have the trajectories on the path given in your image above?

**Comment by haoxuanluo731** [comment]
I have check the xtc,it do have the trajectories,    If you run the example we provide, it does work, but when you run your own analysis you get the problem shown in the image that the trajectory cannot be found?this is my problem,can I offer my file to your email,I really want to know what happened

**Comment by StefanGIT** [comment]
I saw you have also opened threads in the MD-IFP repository. Can you describe your problem there with more details and give the position in code where the error happens and what Jupyter notebook you are using? I will close the issue here as it is not a GROMACAS-RAMD  issue.

**Comment by haoxuanluo731** [comment]
okk

**Comment by haoxuanluo731** [comment]
I have provide problem in MD-IFP
