### ISSUE TITLE
the figure generated by tauRAMD is not correct

### ISSUE THREAD

**Issue by autodataming** [HITS-MCM/gromacs-ramd#47]
I have 10 replicas.

(]$ **cat times_1.dat** 
Replica10/Replica10_ramd.log:==== RAMD ==== GROMACS will be stopped after 609950 steps.
Replica1/Replica1_ramd.log:==== RAMD ==== GROMACS will be stopped after 141200 steps.
Replica2/Replica2_ramd.log:==== RAMD ==== GROMACS will be stopped after 297250 steps.
Replica3/Replica3_ramd.log:==== RAMD ==== GROMACS will be stopped after 110800 steps.
Replica4/Replica4_ramd.log:==== RAMD ==== GROMACS will be stopped after 144100 steps.
Replica5/Replica5_ramd.log:==== RAMD ==== GROMACS will be stopped after 111700 steps.
Replica6/Replica6_ramd.log:==== RAMD ==== GROMACS will be stopped after 528550 steps.
Replica7/Replica7_ramd.log:==== RAMD ==== GROMACS will be stopped after 408600 steps.
Replica8/Replica8_ramd.log:==== RAMD ==== GROMACS will be stopped after 157150 steps.
Replica9/Replica9_ramd.log:==== RAMD ==== GROMACS will be stopped after 273650 steps.

**python tauRAMD.py  times_1.dat** 
Data found: times_1.dat
************ Dissociation times for times_1.dat ****************
[1.2199 0.2824 0.5945 0.2216 0.2882 0.2234 1.0571 0.8172 0.3143 0.5473]

 ==============   Bootstrapping and computation of tau for each replica==================

[ 1.2199  0.2824  0.5945  0.2216  0.2882  0.2234  1.0571  0.8172  0.3143
  0.5473 55.     55.     55.     55.     55.    ]
 Relative res. time and SD:  0.83 0.17 KS test: 0.33
-----------------------------------------------------------------
Residence times for 1 replicas, mean: 0.8  std: 0.0
![res_times](https://github.com/user-attachments/assets/7763fb6e-552f-4f4d-ae0b-b188eec78408)
![res_times_summary](https://github.com/user-attachments/assets/13d8e37e-d14f-4237-bd41-e4b1acba79c3)
just only 1 replica on the figure.

Could you give me some suggestions? Thank you!

**Comment by BerndDoser** [comment]
Please avoid opening duplicate issues. This is more related to https://github.com/HITS-MCM/tauRAMD/issues/2.
